[tool.poetry]
name = "gpbp-osm"
version = "0.1.0"
description = ""
authors = ["EiriniK <Eirini.Kousathana@ortec.com>"]
readme = "README.md"
packages = [{include = "gpbp_osm"}]

[tool.poetry.dependencies]
python = "^3.10"
geopandas = ">=0.11"
networkx = ">=2.8"
pyproj = ">=3.3"
requests = ">=2.28"
rtree = ">=1.0"
osmnx = "^1.2.2"
ipykernel = "^6.16.2"
folium = "^0.13.0"
wget = "^3.2"
pycountry = "^22.3.5"
countryinfo = "^0.1.2"
gadm = {git = "https://github.com/loicdtx/pygadm.git"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
